apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-balloon
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: autoscaler-balloon
  template:
    metadata:
      labels:
        app: autoscaler-balloon
    spec:
      priorityClassName: cluster-autoscaler-balloon
      terminationGracePeriodSeconds: 0
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.9
          resources:
            requests:
              memory: 1Gi
              cpu: 10m
            limits:
              memory: 1Gi
              cpu: 10m
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: autoscaler-balloon
              topologyKey: kubernetes.io/hostname
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
