---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
spec:
  destination:
    namespace: cnpg
    server: https://kubernetes.default.svc
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: v0.27.*
  project: cnpg
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
