apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: monitoring
  source:
    path: charts/kube-prometheus-stack
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: HEAD
    helm:
      valuesObject:
        crds:
          enabled: false
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        prometheus:
          ingress:
            enabled: true
            ingressClassName: tailscale
            pathType: ImplementationSpecific
            paths: [ / ]
            hosts:
              - prometheus.gentoo-mine.ts.net
            tls:
              - hosts:
                  - prometheus.gentoo-mine.ts.net
          prometheusSpec:
            replicas: 1
            priorityClassName: cluster-low
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                memory: 1Gi
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            affinity:
              nodeAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    preference:
                      matchExpressions:
                        - key: kubernetes.io/hostname
                          operator: In
                          values:
                            - pi.home.arpa
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn-durable
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 50Gi
        prometheusOperator:
          priorityClassName: cluster-low
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  preference:
                    matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - pi.home.arpa
          admissionWebhooks:
            certManager:
              enabled: true
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
        kubeControllerManager:
          enabled: false
        cleanPrometheusOperatorObjectNames: true
        defaultRules:
          create: false
