apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  source:
    path: charts/kube-prometheus-stack
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: HEAD
    helm:
      valuesObject:
        crds:
          enabled: false # configured elsewhere in this repo
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        prometheus:
          ingress:
            enabled: true
            ingressClassName: tailscale
            pathType: ImplementationSpecific
            paths: [ / ]
            hosts:
              - prometheus.gentoo-mine.ts.net
            tls:
              - hosts:
                  - prometheus.gentoo-mine.ts.net
          prometheusSpec:
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            affinity:
              nodeAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    preference:
                      matchExpressions:
                        - key: kubernetes.io/hostname
                          operator: In
                          values:
                            - pi.home.arpa
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn-durable
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 50Gi
        prometheusOperator:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  preference:
                    matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - pi.home.arpa
          admissionWebhooks:
            certManager:
              enabled: true
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
        kubeControllerManager:
          enabled: false
        cleanPrometheusOperatorObjectNames: true
        defaultRules:
          create: false
