apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tailscale
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  destinations:
  - namespace: tailscale
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
