apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
spec:
  project: tailscale
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    targetRevision: 1.96.*
    chart: tailscale-operator
    helm:
      values: |
        operatorConfig:
          defaultTags:
            - "tag:k8s-operator"
          priorityClassName: cluster-low
        proxyConfig:
          defaultTags: "tag:k8s-operator"
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
