apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: barcodebuddy-config
  namespace: barcodebuddy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
