apiVersion: v1
kind: ConfigMap
metadata:
  name: grocy-config
  namespace: grocy
data:
  GROCY_CURRENCY: "GBP"
  GROCY_DEFAULT_LOCALE: "en_GB"
  GROCY_CALENDAR_FIRST_DAY_OF_WEEK: "1"
  GROCY_FEATURE_FLAG_CHORES: "false"
  GROCY_FEATURE_FLAG_TASKS: "false"
  GROCY_FEATURE_FLAG_BATTERIES: "false"
  GROCY_FEATURE_FLAG_EQUIPMENT: "false"
  GROCY_FEATURE_FLAG_CALENDAR: "false"
  GROCY_FEATURE_FLAG_LABEL_PRINTER: "false"
  GROCY_FEATURE_FLAG_THERMAL_PRINTER: "false"
  GROCY_FEATURE_FLAG_STOCK_PRICE_TRACKING: "false"
  GROCY_FEATURE_FLAG_STOCK_PRODUCT_FREEZING: "false"
  GROCY_FEATURE_FLAG_RECIPES_MEALPLAN: "false"
  GROCY_DISABLE_AUTH: "true"
  GROCY_ENTRY_PAGE: "stock"
