apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcloud-cluster-autoscaler
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: hetzner
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    targetRevision: 9.*.*
    chart: cluster-autoscaler
    helm:
      valuesObject:
        image:
          tag: v1.33.4
        cloudProvider: hetzner
        autoscalingGroups:
          - name: hcloud-cx22-nbg1
            minSize: 0
            maxSize: 3
            instanceType: cx22
            region: nbg1
        extraEnv:
          HCLOUD_IMAGE: ubuntu-24.04
        extraEnvSecrets:
          HCLOUD_TOKEN:
            name: hcloud
            key: token
          HCLOUD_CLOUD_INIT:
            name: hcloud-init-data
            key: cloud-init
        extraArgs:
          scale-down-delay-after-add: 50m
          scale-down-unneeded-time: 5m
          skip-nodes-with-system-pods: "false"
        nodeSelector:
          kubernetes.io/hostname: saraneth
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            effect: NoSchedule
        priorityClassName: system-cluster-critical
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
