apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.*
    chart: argo-cd
    helm:
      valuesObject:
        global:
          priorityClassName: cluster-critical
          domain: argocd.gentoo-mine.ts.net
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  preference:
                    matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - pi.home.arpa
        configs:
          cm:
            admin.enabled: false
            accounts.claude: apiKey
          params:
            server.insecure: "true"
            server.disable.auth: "true"
          rbac:
            policy.default: role:admin
        dex:
          enabled: false
        server:
          ingress:
            enabled: true
            ingressClassName: tailscale
            annotations:
              tailscale.com/hostname: argocd
            hosts:
              - argocd
            tls:
              - hosts:
                  - argocd
