apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.*
    chart: argo-cd
    helm:
      values: |
        global:
          domain: argocd.k3s.fluv.net
        configs:
          cm:
            oidc.config.name: Authentik
            oidc.config.issuer: https://authentik.k3s.fluv.net/application/o/argo-cd/
            oidc.config.clientID: $authentik:client-id
            oidc.config.clientSecret: $authentik:client-secret
            oidc.tls.insecure.skip.verify: true
        dex:
          enabled: false
        server:
          ingress:
            enabled: true
            tls: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-production"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
