apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: barcodebuddy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: barcodebuddy
  project: default
  source:
    path: barcodebuddy
    repoURL: https://github.com/zuzak/kube.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
