apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.10.*
      helm:
        valuesObject:
          preUpgradeChecker:
            jobEnabled: false
          csi:
            attacher:
              replicaCount: 1
            provisioner:
              replicaCount: 1
            resizer:
              replicaCount: 1
            snapshotter:
              replicaCount: 1
          longhornUI:
            replicas: 1
          persistence:
            defaultClassReplicaCount: 2
          metrics:
            serviceMonitor:
              enabled: true
          ingress:
            enabled: true
            tls: true
            ingressClassName: tailscale
            host: longhorn.gentoo-mine.ts.net
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
