apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: claude
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: claude
  source:
    repoURL: https://github.com/zuzak/kube.git
    path: claude
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    namespace: claude
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
