apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-mcp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: claude
  source:
    repoURL: https://github.com/pab1it0/prometheus-mcp-server.git
    path: charts/prometheus-mcp-server
    targetRevision: HEAD
    helm:
      valuesObject:
        prometheus:
          url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          disableLinks: "true"
        mcp:
          transport: sse
        livenessProbe:
          httpGet:
            path: /sse
            port: http
        readinessProbe:
          httpGet:
            path: /sse
            port: http
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 128Mi
  destination:
    namespace: claude
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
